# This is a custome ubuntu images with SSH, telnet, and net-tools alrady installed.
FROM ubuntu:xenial
MAINTAINER Govinda <gkdangal@gmail.com>
RUN apt-get update -y
RUN apt-get install -y telnet openssh-server net-tools

